### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by tariqdaouda** [tariqdaouda/pyGeno#12]
Make pyGeno compatible with python 3.

**Comment by brennv** [comment]
This! Forking now, any advice before I get started? :)

**Comment by xguse** [comment]
The fact that this is written in py2 is a great disappointment to me.

**Comment by tariqdaouda** [comment]
Do you mean that you really would like to use pyGeno, but the fact that for the time being it's only py2 prevents you form doing so?

**Comment by xguse** [comment]
Mostly, yes. All of my own code exists as Py3 and in environments populated with Py3.



--

W. Augustine Dunn III, PhD
Research Fellow
Boston Children's Hospital
Gastroenterology
Laboratory of Scott Snapper MD, PhD

Abbreviated CV: http://bit.ly/gusdunn_short_cv

http://about.me/wadunn
w.gus.dunn@gmail.com<mailto:w.gus.dunn@gmail.com>
Gus.Dunn@childrens.harvard.edu<mailto:Gus.Dunn@childrens.harvard.edu>

To send encrypted mail, use my public key:
GPG KeyID - 39A5CC70

http://tiny.cc/gus_dunn_pub_key1

**Comment by tariqdaouda** [comment]
I'll start working on it as soon as I can. In the meantime if you want to start working on it, I'd be very happy to help and mention your contribution.

**Comment by xguse** [comment]
For sure and I am interested in contributing. Probably can't in the next few days but hopefully in a week or so.

**Comment by tariqdaouda** [comment]
That's great news.

**Comment by tariqdaouda** [comment]
Ported to py3!

**Comment by courcelm** [comment]
Merci! Youppi!!!
