### ISSUE TITLE
pyGeno does not 

### ISSUE THREAD

**Issue by oktaykaplan** [tariqdaouda/pyGeno#15]
The following issue has arisen 

Using the pip install pyGeno command, pyGeno was installed as seen below.

"C:\Windows\system32>pip install pyGeno
Requirement already satisfied (use --upgrade to upgrade): pyGeno in c:\python27\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): rabaDB>=1.0.2 in c:\python27\lib\site-packages (from pyGeno)
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command."

However, the genome import did not work with suggested command "import pyGeno.bootstrap as B " 

It has given the following error:

"Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pyGeno\__init__.py", line 4, in <module>
    pyGeno_init()
  File "C:\Python27\lib\site-packages\pyGeno\configuration.py", line 103, in pyGeno_init
    db = rabaDB.rabaSetup.RabaConnection(pyGeno_RABA_NAMESPACE)
  File "C:\Python27\lib\site-packages\rabaDB\rabaSetup.py", line 21, in __call__
    cls._instances[key] = type.__call__(cls, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rabaDB\rabaSetup.py", line 48, in __init__
    self.connection = sq.connect(RabaConfiguration(namespace).dbFile)
sqlite3.OperationalError: unable to open database file"

When we checked the pyGene in the C:\Python27\Lib\site-packages, both pyGene and rabaDB are found in that folder. We then uninstalled pyGene and Python 2.7.12 and reinstalled them to resolve the problem but the problem persists. Unfortunately, we could not figure out a way to resolve the problem. 

Incompatibility of  pyGene with non-English Windows 10 is the only thing we could think of as there are non-english characters. Any idea what to do?

**Comment by tariqdaouda** [comment]
This is sqlite3 screaming inside of [rabaDB](https://github.com/tariqdaouda/rabaDB) (pyGeno's backend) that the database file cannot be opened. pyGeno will automatically create a folder `.pyGeno` in your home directory. For windows 10, it is usually something like:` C:\Users\<username>\.pyGeno` . This folder will contain the complete database of pyGeno, and most importantly here, a file called `pyGenoRaba.db`, which is the file that rabaDB is looking for here.

This could be a rights problem where the python script does not have enough credentials to create the folder and files inside of it. The first thing to check is if the file ` C:\Users\<username>\.pyGeno\pyGenoRaba.db` exists. If not this might be a problem with your windows configuration. If it is there you can try to open it using any sqlite browser, such as this one:[http://sqlitebrowser.org/](http://sqlitebrowser.org/), and see if anything is wrong with it.

I have just pushed two new versions of pyGeno and rabaDB on github (not yet on pypi) the current version of rabaDB should also print the complete file path file when this error happens.
If the error persists, and you don't mind uninstalling the pypi versions and replacing them the cutting edge versions on github. That should give us more information.
