### ISSUE TITLE
no module named configuration

### ISSUE THREAD

**Issue by im281** [tariqdaouda/pyGeno#22]
when calling
from pyGeno.Genome import *

ImportError: No module named 'configuration'

**Comment by tariqdaouda** [comment]
I've just tried the github and the pypi version, both work for me. Can you give me more details?

**Comment by im281** [comment]
I install using:

C:\Users\Owner>pip install pyGeno
Requirement already satisfied (use --upgrade to upgrade): pyGeno in c:\users\owner\anaconda3\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): rabaDB>=1.0.2 in c:\users\owner\anaconda3\lib\site-packages (from pyGeno)

But then when I try to run the examples I get:
ImportError: No module named 'configuration'

**Comment by im281** [comment]
File "C:\Users\Owner\Anaconda3\lib\site-packages\pyGeno\__init__.py", line 3, in <module>
    from configuration import pyGeno_init

ImportError: No module named 'configuration'

**Comment by tariqdaouda** [comment]
Could you try the git version? If not I will be pushing new versions in the upcoming days of both pyGeno and rabaDB to pypi. You'd have to upgrade you pypi pacakges.

**Comment by asadrahman-horizon** [comment]
This tool has a lot of potential, unfortunately I am facing similar issues. Any progress on upgrading it to python 3 version?

**Comment by tariqdaouda** [comment]
Unfortunately no. Since most of my development time is taken by Mariana, my work on pyGeno is for the moment limited to maintenance and small improvements on the 2.7 version.
However, There is already an open issue on py3 support [thread](https://github.com/tariqdaouda/pyGeno/issues/12) if it gathers enough attention I will port it to py3.

**Comment by tariqdaouda** [comment]
I'm closing this issue as it has been ported to py3.
