### ISSUE TITLE
Error: Genome object instantiation

### ISSUE THREAD

**Issue by Symmo** [tariqdaouda/pyGeno#23]
Hi,
When I tried to create a Genome object, I received the following error: 

```
from pyGeno.Genome import *
g = Genome(name = "GRCh37.75")
```

KeyError: "Couldn't find any object that fit the arguments you've prodided to the constructor".

I installed pyGeno with pip.

Thanks.

**Comment by chaomacau** [comment]
I am having the same issue. Could you explain how you fix it? Thank you!

**Comment by tariqdaouda** [comment]
You should first import the genome, you can do it by using the bootstrap module as show [here](https://github.com/tariqdaouda/pyGeno#batteries-included-bootstraping).
