### ISSUE TITLE
AgnosticSNP quality is a string and should be float

### ISSUE THREAD

**Issue by courcelm** [tariqdaouda/pyGeno#26]
AgnosticSNP quality is a string and should be float

This is an issue for comparison because in python 2.7:

>>> '0.001' > 20
True

For SNP filter this will silently fail:

        def filter(self, chromosome, **kwargs):

            for snp_set, snp in kwargs.iteritems():

                    if snp.quality > self.threshold:

                        return SequenceSNP(snp.alt)

snp.quality must be cast to float to obtain the expected result

**Comment by tariqdaouda** [comment]
True. Where is that coming from?

**Comment by courcelm** [comment]
Fixed in 1.3.1
