### ISSUE TITLE
Quick example on the home page does not work

### ISSUE THREAD

**Issue by ialbert** [tariqdaouda/pyGeno#3]
The quick example on the homepage contains several typos and omissions (six in total!) that make the code unrunnable.

In general, but especially the quick example should be run through python to ensure that it works before pasting it into the docs. It also should be a self sufficient that does not need other information to run. 

Since we are here I will make a note that this page does not do a good job in demonstrating what the library actually does.  The actually interesting part for me as a python programmer is not  that the library can extract the sequences for ensemble proteins - that is a job I can do with many tools already.

What interest me getting to the next level is combining and querying the Ensemble genes and the SNPs at the same time.

But the quick start stops at the most interesting line:

    g = Genome(name = "GRCh37.75", SNPs = ["STY21_RNA"], SNPFilter = MyFilter()

ok there is promise here, but now what can I do here once I have this construct? What is `MyFilter()` what does that do.

**Comment by tariqdaouda** [comment]
Hi,

pyGeno is also intended to be used by people with less technical abilities than you have, and the quick example is there to showcase the package's abilities, hence the simplified first example and the "...". MyFilter() is simply there to signal that you can easily plug your own filter if you need to.

Filters are simple objects that you create by defining classes that inherit from **pyGeno.SNPFiltering.SNPFilter**. There's an example at the end of the Readme and another one at the end of the quickstart guide in the documentation: http://pygeno.iric.ca/quickstart.html#personalized-genomes.

However I think you're right, I should put more emphasis on the personalized genomes.
