### ISSUE TITLE
mutant  (SNV/indel) protein sequence generation

### ISSUE THREAD

**Issue by haoye2015** [tariqdaouda/pyGeno#33]
Hi Tariq,

Thank you for helping me on loading genome yesterday.

I further tested pyGeno on generating a mutant protein sequence. 

Actually, I uploaded two ERBB2 variants and two EGFR indels with known AA change annotation,  (ENST00000445658:c.T1888G:p.W630G and ENST00000445658:exon16:c.A1879G:p.S627G)

(ENST00000455089:c.2100_2114del:p.700_705del and ENST00000455089:c.2161_2162insTGGCCAGCG:p.M721delinsMASV)

 However, I find the **mutant protein sequence generated by pyGeno is exactly the same with the corresponding reference protein sequence**. **It seems the filter doesn't work.** Would you point out what's wrong with my commands in pyGeno. ( Also, the test_var file was enclosed in attachment.)  **If there is anyway to efficiently implement both indels and SNP in one Filter?**

Thank you.

Best

Hao

-------------------------------------------------------------------------------------------------------------------

`
>>> from pyGeno.importation.Genomes import *
>>> from pyGeno.importation.SNPs import *
>>> from pyGeno.Genome import *
>>> from pyGeno.Transcript import Transcript
>>>from pyGeno.SNPFiltering import SNPFilter
>>>from pyGeno.SNPFiltering import SequenceSNP
>>>from pyGeno.SNPFiltering import SequenceInsert
>>>from pyGeno.SNPFiltering import SequenceDel
>>> importSNPs('/test_snp_path/test_var')
>>> class QMax_gt_filter(SNPFilter) :
...     def __init__(self, threshold) :
...             self.threshold = threshold
...     def filter(self, chromosome, test_var = None) :
...             if test_var.quality > self.threshold :
...                     #other possibilities of return are SequenceInsert(<bases>), SequenceDel(<length>)
...                     if test_var.alt[0] == '-':
...                             return SequenceDel(len(test_var.ref))
...                     if test_var.ref[0] == '-':
...                             return SequenceInsert(test_var.alt)
...                     elif test_var.alt[0] != '-' and test_var.ref[0] != '-':
...                             return SequenceSNP(test_var.alt)
...             return None

>>> mut_G = Genome(name = 'GRCh37.75', SNPs = 'test_var', SNPFilter = QMax_gt_filter(8))
>>> mut_trans = mut_G.get(Transcript, id ='ENST00000445658')
>>> mut_prot = mut_trans[0].protein
>>> mut_prot.sequence

>>> ref_G = Genome(name = 'GRCh37.75')
>>> ref_trans = ref_G.get(Transcript, id ='ENST00000445658')
>>> ref_prot = ref_trans[0].protein
>>> ref_prot.sequence
`

mut_prot  sequence output:
'MELAALCRWGLLLALLPPGAASTQDNYLSTDVGSCTLVCPLHNQEVTAEDGTQRCEKCSKPCARVCYGLGMEHLREVRAVTSANIQEFAGCKKIFGSLAFLPESFDGDPASNTAPLQPEQLQVFETLEEITGYLYISAWPDSLPDLSVFQNLQVIRGRILHNGAYSLTLQGLGISWLGLRSLRELGSGLALIHHNTHLCFVHTVPWDQLFRNPHQALLHTANRPEDECVGEGLACHQLCARGHCWGPGPTQCVNCSQFLRGQECVEECRVLQGLPREYVNARHCLPCHPECQPQNGSVTCFGPEADQCVACAHYKDPPFCVARCPSGVKPDLSYMPIWKFPDEEGACQPCPINCTHSCVDLDDKGCPAEQRASPLTSIISAVVGILLVVVLGVVFGILIKRRQQKIRKYTMRRLLQETELVEPLTPSGAMPNQAQMRILKETELRKVKVLGSGAFGTVYKGIWIPDGENVKIPVAIKVLRENTSPKANKEILDEAYVMAGVGSPYVSRLLGICLTSTVQLVTQLMPYGCLLDHVRENRGRLGSQDLLNWCMQIAKGMSYLEDVRLVHRDLAARNVLVKSPNHVKITDFGLARLLDIDETEYHADGGKVPIKWMALESILRRRFTHQ**S**DV**W**SYGVTVWELMTFGAKPYDGIPAREIPDLLEKGERLPQPPICTIDVYMIMVKCWMIDSECRPRFRELVSEFSRMARDPQRFVVIQNEDLGPASPLDSTFYRSLLEDDDMGDLVDAEEYLVPQQGFFCPDPAPGAGGMVHHRHRSSSTRSGGGDLTLGLEPSEEEAPRSPLAPSEGAGSDVFDGDLGMGAAKGLQSLPTHDPSPLQRYSEDPTVPLPSETDGYVAPLTCSPQPEYVNQPDVRPQPPSPREGPLPAARPAGATLERPKTLSPGKNGVVKDVFAFGGAVENPEYLTPQGGAAPQPHPPPAFSPAFDNLYYWDQDPPERGAPPSTFKGTPTAENPEYLGLDVPV`

ref_prot.sequence output:
'MELAALCRWGLLLALLPPGAASTQDNYLSTDVGSCTLVCPLHNQEVTAEDGTQRCEKCSKPCARVCYGLGMEHLREVRAVTSANIQEFAGCKKIFGSLAFLPESFDGDPASNTAPLQPEQLQVFETLEEITGYLYISAWPDSLPDLSVFQNLQVIRGRILHNGAYSLTLQGLGISWLGLRSLRELGSGLALIHHNTHLCFVHTVPWDQLFRNPHQALLHTANRPEDECVGEGLACHQLCARGHCWGPGPTQCVNCSQFLRGQECVEECRVLQGLPREYVNARHCLPCHPECQPQNGSVTCFGPEADQCVACAHYKDPPFCVARCPSGVKPDLSYMPIWKFPDEEGACQPCPINCTHSCVDLDDKGCPAEQRASPLTSIISAVVGILLVVVLGVVFGILIKRRQQKIRKYTMRRLLQETELVEPLTPSGAMPNQAQMRILKETELRKVKVLGSGAFGTVYKGIWIPDGENVKIPVAIKVLRENTSPKANKEILDEAYVMAGVGSPYVSRLLGICLTSTVQLVTQLMPYGCLLDHVRENRGRLGSQDLLNWCMQIAKGMSYLEDVRLVHRDLAARNVLVKSPNHVKITDFGLARLLDIDETEYHADGGKVPIKWMALESILRRRFTHQ**S**DV**W**SYGVTVWELMTFGAKPYDGIPAREIPDLLEKGERLPQPPICTIDVYMIMVKCWMIDSECRPRFRELVSEFSRMARDPQRFVVIQNEDLGPASPLDSTFYRSLLEDDDMGDLVDAEEYLVPQQGFFCPDPAPGAGGMVHHRHRSSSTRSGGGDLTLGLEPSEEEAPRSPLAPSEGAGSDVFDGDLGMGAAKGLQSLPTHDPSPLQRYSEDPTVPLPSETDGYVAPLTCSPQPEYVNQPDVRPQPPSPREGPLPAARPAGATLERPKTLSPGKNGVVKDVFAFGGAVENPEYLTPQGGAAPQPHPPPAFSPAFDNLYYWDQDPPERGAPPSTFKGTPTAENPEYLGLDVPV`

manifest.ini

`[package_infos]
description = mutant peptide generation
maintainer = Tariq Daouda
maintainer_contact = tariq.daouda@umontreal.ca
version = 1

[set_infos]
species = human
name = test_var
type = Agnostic
source = TCGA variants

[snps]
filename = test_var.txt
`

test_var.txt

chromosomeNumber	uniqueId	start	end	ref	alt	quality	caller
17	1	37881637	37881637	A	G	255	GATK
17	2	37881646	37881646	T	G	255	GATK
7	3	55242465	55242479	GGAATTAAGAGAAGC	-	255	GATK
7	4	55242465	55242479	-	TGGCCAGCG	255	GATK

**Comment by tariqdaouda** [comment]
Hi Hao,

It seems like the reference is actually a **G** in GRCh35.75. I tracked down the SNPs and they belong to the exon 15.

I wrote this small script to demonstrate that the insertion takes place. This custom filter prints any SNP encountered and inserts an "R" every time:

```
from pyGeno.Genome import *
from pyGeno.SNPFiltering import *

class F(SNPFilter) :
    def __init__(self, threshold) :
        self.threshold = threshold
    
    def filter(self, chromosome, test_var = None) :
        print test_var, test_var.alt
        if test_var.quality > self.threshold :
            return SequenceSNP("R")
        return None

mut_G = Genome(name ='GRCh37.75', SNPs = 'test_var', SNPFilter=F(8))
ref = Genome(name ='GRCh37.75')
Transcript.ensureGlobalIndex('id')
mut_trans = mut_G.get(Transcript, id ='ENST00000445658')[0]
ref_trans = ref.get(Transcript, id ='ENST00000445658')[0]

print mut_trans.exons[15].sequence
print ref_trans.exons[15].sequence
print mut_trans.exons[15].sequence == ref_trans.exons[15].sequence
```

When I run it I get:

```
AgnosticSNP> start: 37881637, end: 37881637, quality: 255.0, caller GATK, alt: G, ref: A G
AgnosticSNP> start: 37881646, end: 37881646, quality: 255.0, caller GATK, alt: G, ref: T G
```
GTGCCCATCAAGTGGATGGCGCTGGAGTCCATTCTCCGCCGGCGGTTCACCCACCAGA**R**TGATGTGT**R**GAGTTATG
GTGCCCATCAAGTGGATGGCGCTGGAGTCCATTCTCCGCCGGCGGTTCACCCACCAGAGTGATGTGTGGAGTTATG


It is also possible to implement filters that insert SNPs but also support indels. You just have to return a SequenceDel object for a deletion, a SequenceInsert for an insertion, and a SequenceSNP for a SNP. You can find more information [here](http://bioinfo.iric.ca/~daoudat/pyGeno/snp_filter.html).

Best,

**Comment by haoye2015** [comment]
Hi tariq,

Thanks for your help. I guess the problem is caused by the discordance between UCSC hg19 and GRCh37.  Actualy, the coordinate in original text_var.txt was generated from vcf file of hg19.  However, Ensembl uses a one-based coordinate system, UCSC uses a zero-based coordinate system. [http://www.ensembl.org/Help/Faq?id=286](url)

I modify the concordance of test_var.txt.

the revised test_var.txt was

```
chromosomeNumber	uniqueId	start	end	ref	alt	quality	caller
17	1	37881636	37881636	A	G	255	GATK
17	2	37881645	37881645	T	G	255	GATK
7	3	55242464	55242478	GGAATTAAGAGAAGC	-	255	GATK
7	4	55248997	55248997	-	TGGCCAGCG	255	GATK
```


Then I used the your filter and commands, 'R' are  **exactly replace at the right loc.**
`AgnosticSNP> start: 37881636, end: 37881636, quality: 255.0, caller GATK, alt: None, ref: A None
AgnosticSNP> start: 37881645, end: 37881645, quality: 255.0, caller GATK, alt: None, ref: T None
GTGCCCATCAAGTGGATGGCGCTGGAGTCCATTCTCCGCCGGCGGTTCACCCACCAGRGTGATGTGRGGAGTTATG
GTGCCCATCAAGTGGATGGCGCTGGAGTCCATTCTCCGCCGGCGGTTCACCCACCAGAGTGATGTGTGGAGTTATG
`

However, when I changed the Filter as 

```
class QMax_gt_filter(SNPFilter) :
	def __init__(self, threshold) :
		self.threshold = threshold
	def filter(self, chromosome, test_var = None) :
		print test_var, test_var.ref, test_var.alt
		if test_var.quality > self.threshold :
			if test_var.alt != '-' and test_var.ref != '-':
				return SequenceSNP(test_var.alt)
			elif test_var.alt == '-':
				return SequenceDel(len(test_var.ref))
			elif test_var.ref == '-':
				return SequenceInsert(test_var.alt)
		return None 
```

An error was reported as 

```
>>> mut_G = Genome(name ='GRCh37.75', SNPs = 'test_var', SNPFilter=QMax_gt_filter(8))
>>> mut_trans = mut_G.get(Transcript, id ='ENST00000445658')
>>> print mut_trans[0].exons[15].sequence
AgnosticSNP> start: 37881636, end: 37881636, quality: 255.0, caller GATK, alt: None, ref: A A None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yeh/program/Python-2.7.13/lib/python2.7/site-packages/pyGeno/pyGenoObjectBases.py", line 175, in __getattr__
    self._load_sequences()
  File "/home/yeh/program/Python-2.7.13/lib/python2.7/site-packages/pyGeno/pyGenoObjectBases.py", line 238, in _load_sequences
    self._load_data()
  File "/home/yeh/program/Python-2.7.13/lib/python2.7/site-packages/pyGeno/Exon.py", line 78, in _load_data
    data = self.chromosome.getSequenceData(slice(self.start,self.end))
  File "/home/yeh/program/Python-2.7.13/lib/python2.7/site-packages/pyGeno/Chromosome.py", line 126, in getSequenceData
    return self.sequence.getSequenceData(slic)
  File "/home/yeh/program/Python-2.7.13/lib/python2.7/site-packages/pyGeno/Chromosome.py", line 62, in getSequenceData
    sequenceModifier = self.SNPFilter.filter(self.chromosome, **setPolys)
  File "<stdin>", line 8, in filter
  File "/home/yeh/program/Python-2.7.13/lib/python2.7/site-packages/pyGeno/SNPFiltering.py", line 23, in __init__
    self.alleles = uf.encodePolymorphicNucleotide(alleles)
  File "/home/yeh/program/Python-2.7.13/lib/python2.7/site-packages/pyGeno/tools/UsefulFunctions.py", line 254, in encodePolymorphicNucleotide
    for n in sseq :
TypeError: 'NoneType' object is not iterable
```

 **If I changed  QMax_gt_filter as  ( change return  SequenceSNP(test_var.alt)  ------>   return  SequenceSNP('G')) , the correct results could be generated.**

```
class QMax_gt_filter(SNPFilter) :
	def __init__(self, threshold) :
		self.threshold = threshold
	def filter(self, chromosome, test_var = None) :
		print test_var, test_var.ref, test_var.alt
		if test_var.quality > self.threshold :
			if test_var.alt != '-' and test_var.ref != '-':
				return SequenceSNP('G')
			elif test_var.alt == '-':
				return SequenceDel(len(test_var.ref))
			elif test_var.ref == '-':
				return SequenceInsert(test_var.alt)
		return None 

```
**It seems 'return SequenceSNP(test_var.alt), return SequenceDel(len(test_var.ref)), return return SequenceInsert(test_var.alt) were not correctly implemented.** 

I wonder how can I modify QMax_gt_filter, then a personalized genome with all the four variants could be correctly generated.

Best

Hao

**Comment by haoye2015** [comment]
Hi Tariq,

I also wonder **whether pyGeno could create an SNPs object from a simple list (including information of chr, start, end, ref, alleles, quality, caller)**, instead of pyGeno.importation.SNPs.importSNPs from a folder.  
That could be very convenient to generate an customized SNPs object.

for example  in the test_var.txt
```
chromosomeNumber	uniqueId	start	end	ref	alleles	quality	caller
17	1	37881636	37881636	A	G	255	GATK
17	2	37881645	37881645	T	G	255	GATK
7	3	55242464	55242478	GGAATTAAGAGAAGC	-	255	GATK
7	4	55248997	55248997	-	TGGCCAGCG	255	GATK
```
Can I use  the following style to generate an SNPs object in pyGeno

```
data = open(r'test_var.txt','r')
data.readline()
for line in data:
     generate an SNPs objects  from line.
```

**Comment by tariqdaouda** [comment]
Hi Hao,

Yes there are some helper functions that you can use to highlight differences. The first one is [tools.UsefulFunctions.showDifferences](https://github.com/tariqdaouda/pyGeno/blob/bloody/pyGeno/tools/UsefulFunctions.py#L322).

Inside pyGeno, every sequence in pyGeno has a binary equivalent that you can access through the `bin_xxx` attributes, ex: `mut_trans.sequence => mut_trans.bin_sequence`.

Binary sequences have many functions that give you direct access to polymorphisms such has [findPolymorphisms and getProlymorphisms](http://bioinfo.iric.ca/~daoudat/pyGeno/tools.html#binary-sequences). You can directly use these functions or use them to write your own marker functions.

The easiest way to add SNPs is through a datawrap that is then stored in pyGeno's database and accessed as needed. This way pyGeno can automatically deal with non trivial issues, such as exon ordering, stands, offsets due to previous insertions and deletions and change of annotations.

However, if you want to insert polymorphisms on the fly in controlled environments you can also BinarySequence objects or of it's derivative classes NucBinarySequence or AABinarySequence. They would you give a lot of freedom but you would have to take care of SNP placements in you code.

Best,

**Comment by haoye2015** [comment]
Hi Tariq,

That's the exact question How to transform a string to a binary sequence.  
I used the following commands to generate a binary sequence. However, the Polymorphisms returns blank.  How can I get polymorphisms through binary sequence.

```
>>> mut_b_prot = pyGeno.tools.BinarySequence.AABinarySequence(mut_prot)
>>> mut_b_prot
<pyGeno.tools.BinarySequence.AABinarySequence instance at 0x7fd4dc2f16c8>
>>> mut_b_prot.getPolymorphisms()
[]
```
Best

**Comment by tariqdaouda** [comment]
Hi Hao,

You must give it a string as input. You can use "/" to separate nucleotides or AAs polymorphisms or you can use the one character encoding of nucleotides (R = A/G). The provided BinarySequences classes do not handle indels, it is up to you remove or add parts of the sequence using python.

Best,
