### ISSUE TITLE
Error in importing my_SNP.tar.gz 

### ISSUE THREAD

**Issue by Yiming-Shen** [tariqdaouda/pyGeno#36]
Hi, I was trying to import my SNP file and I followed your instruction [here](https://github.com/tariqdaouda/pyGeno/wiki/How-to-create-a-pyGeno-datawrap-to-import-your-data). However, I got the error message as follows:
`Importing polymorphism set: my/path/to/my_SNP.tar.gz... (This may take a while)`
  `Traceback (most recent call last):`
  `File "<stdin>", line 1, in <module>`
  `File "pyGeno/importation/SNPs.py", line 65, in importSNPs`
    `return _importSNPs_dbSNPSNP(setName, species, genomeSource, snpsFile)`
  `File "pyGeno/importation/SNPs.py", line 192, in _importSNPs_dbSNPSNP`
    `snpData = VCFFile(snpsFile, gziped = True, stream = True)`
  `File "pyGeno/tools/parsers/VCFTools.py", line 89, in __init__`
    `self.parse(filename, gziped, stream)`
  `File "pyGeno/tools/parsers/VCFTools.py", line 106, in parse`
    `ll = self.f.readline()`
  `File "/usr/lib/python2.7/gzip.py", line 464, in readline`
    `c = self.read(readsize)`
  `File "/usr/lib/python2.7/gzip.py", line 268, in read`
    `self._read(readsize)`
  `File "/usr/lib/python2.7/gzip.py", line 303, in _read`
    `self._read_gzip_header()`
  `File "/usr/lib/python2.7/gzip.py", line 197, in _read_gzip_header`
    `raise IOError, 'Not a gzipped file'`
`IOError: Not a gzipped file`
 
I zipped both _manifest.ini_ and _snps.txt_ to _my_SNP.tar.gz_ using `tar -cvzf`.

Do you have any idea why this issue comes up and how I could fix this?

Thanks

**Comment by tariqdaouda** [comment]
Hi,

Given the fact that the Error was generated from `gzip`, my bet would be that there is a problem with the compressed archive file. You could check it by doing a simple:

```
import gzip
gzip.open(filename)

```

Alternatively, The new version of pyGeno should also work with simple folders. You can just put the `manifest.ini` into a folder and point to that folder.

Cheers,

**Comment by Yiming-Shen** [comment]
Hi, thanks for the quick response!

I checked `gzip.open(filename)` and it worked fine...

By using the folder method to import my SNP file, I actually got a similar issue:

`Importing polymorphism set:  my/path/to/my_SNP_folder... ... (This may take a while)`
`Traceback (most recent call last):`
  `File "<stdin>", line 1, in <module>`
  `File "pyGeno/importation/SNPs.py", line 65, in importSNPs`
    `return _importSNPs_dbSNPSNP(setName, species, genomeSource, snpsFile)`
  `File "pyGeno/importation/SNPs.py", line 192, in _importSNPs_dbSNPSNP`
    `snpData = VCFFile(snpsFile, gziped = True, stream = True)`
  `File "pyGeno/tools/parsers/VCFTools.py", line 89, in __init__`
    `self.parse(filename, gziped, stream)`
  `File "pyGeno/tools/parsers/VCFTools.py", line 106, in parse`
    `ll = self.f.readline()`
  `File "/usr/lib/python2.7/gzip.py", line 464, in readline`
    c = self.read(readsize)
  `File "/usr/lib/python2.7/gzip.py", line 268, in read`
    `self._read(readsize)`
  `File "/usr/lib/python2.7/gzip.py", line 303, in _read`
    `self._read_gzip_header()`
  `File "/usr/lib/python2.7/gzip.py", line 197, in _read_gzip_header`
    `raise IOError, 'Not a gzipped file'`
`IOError: Not a gzipped file`

It seems that the programme is still trying to treat the normal files in that folder as gzipped ones. So I changed the _SNPs.py_ file in line 192 from
`snpData = VCFFile(snpsFile, gziped = True, stream = True)`
to
`snpData = VCFFile(snpsFile, gziped = False, stream = True)`

Then, a new error appeared:

`Importing polymorphism set: my/path/to/my_SNP_folder... (This may take a while)`
`Traceback (most recent call last):`
  `File "<stdin>", line 1, in <module>`
  `File ".../pyGeno/pyGeno/bootstrap.py", line 110, in importSNPs`
    `PS.importSNPs(path)`
  `File ".../pyGeno/pyGeno/importation/SNPs.py", line 65, in importSNP                       s`
    `return _importSNPs_dbSNPSNP(setName, species, genomeSource, snpsFile)`
  `File ".../pyGeno/pyGeno/importation/SNPs.py", line 192, in _importS                       NPs_dbSNPSNP`
    `snpData = VCFFile(snpsFile, gziped = False, stream = True)`
  `File ".../pyGeno/pyGeno/tools/parsers/VCFTools.py", line 89, in __i                       nit__`
    `self.parse(filename, gziped, stream)`
  `File ".../pyGeno/pyGeno/tools/parsers/VCFTools.py", line 125, in pa                       rse`
    `value = sv[1]`
`IndexError: list index out of range`

I figured this could be due to the comments lines, so I removed all the comments lines in my original VCF file _snps.txt_. 
Then I got:

`Importing polymorphism set:  my/path/to/my_SNP_folder... (This may take a while)`
`Traceback (most recent call last):`
  `File "<stdin>", line 1, in <module>`
  `File ".../pyGeno/pyGeno/bootstrap.py", line 110, in importSNPs`
    `PS.importSNPs(path)`
  `File ".../pyGeno/pyGeno/importation/SNPs.py", line 65, in importSNPs`
    `return _importSNPs_dbSNPSNP(setName, species, genomeSource, snpsFile)`
  `File ".../pyGeno/pyGeno/importation/SNPs.py", line 197, in _importSNPs_dbSNPSNP`
    `for snpEntry in snpData :`
  `File ".../pyGeno/pyGeno/tools/parsers/VCFTools.py", line 171, in next`
    `return VCFEntry(self, line, self.currentPos)`
  `File ".../pyGeno/pyGeno/tools/parsers/VCFTools.py", line 24, in __init__`
    `filt, value = info_value.split('=')`
`UnboundLocalError: local variable 'info_value' referenced before assignment`

I assumed this `info_value` actually refers to `filter_value` (please correct me if I am not making any sense) so I changed it to the latter and re-import again after which I received:

`Importing polymorphism set: my/path/to/my_SNP_folder... (This may take a while)`
`Traceback (most recent call last):`
  `File "<stdin>", line 1, in <module>`
  `File "/data/home/shenym/projects/pyGeno/pyGeno/bootstrap.py", line 110, in importSNPs`
   ` PS.importSNPs(path)`
  `File "/data/home/shenym/projects/pyGeno/pyGeno/importation/SNPs.py", line 65, in importSNPs`
    `return _importSNPs_dbSNPSNP(setName, species, genomeSource, snpsFile)`
  `File "/data/home/shenym/projects/pyGeno/pyGeno/importation/SNPs.py", line 197, in _importSNPs_dbSNPSNP`
    `for snpEntry in snpData :`
  `File "/data/home/shenym/projects/pyGeno/pyGeno/tools/parsers/VCFTools.py", line 171, in next`
    `return VCFEntry(self, line, self.currentPos)`
  `File "/data/home/shenym/projects/pyGeno/pyGeno/tools/parsers/VCFTools.py", line 24, in __init__`
    `filt, value = filter_value.split('=')`
`ValueError: need more than 1 value to unpack`

I am lost now. As far as I know, the FILTER field of VCF file does not have the format of <key>=<value>, while the next field INFO does. Is is possible that you mean the INFO field not the FILTER field here? (or probably I misunderstood the whole thing at the very beginning.

Cheers

**Comment by tariqdaouda** [comment]
Humm, yes the VCF file could be the problem, but it's hard to tell without having a look at it. VCF is a complicated format and the parser (`tools.parsers.VCFTools.VCFFile
`) is not designed to handle every case. It is mainly there to handle average usage and dbSNP files.

The prefered way to add SNPs into pyGeno is through the Agnostic SNP [format](http://pygeno.iric.ca/datawraps.html). It's just a simple straightforward tab-delimited file it really limits the bad surprises you can get.

Cheers,

**Comment by Yiming-Shen** [comment]
Thanks, I would look into the Agnostic SNP format and try to find a proper way to convert VCF files

**Comment by tariqdaouda** [comment]
Yes, pyGeno uses python convention of 0 based indices everywhere. It's simpler this way.

**Comment by Yiming-Shen** [comment]
Sure! Thanks again :)

**Comment by tariqdaouda** [comment]
You're welome, I'm here to help.
