### ISSUE TITLE
Unsupported translation of selenocysteine

### ISSUE THREAD

**Issue by courcelm** [tariqdaouda/pyGeno#39]
Proteins with a selenocysteine are translated with a stop codon instead of U. GTF file stores codon position of selenocysteine.

2	ensembl_havana	Selenocysteine	84670381	84670383	.	-	.	gene_id "ENSMUSG00000076437"; gene_version "10"; transcript_id "ENSMUST00000117299"; transcript_version "8"; gene_name "Selenoh"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; havana_gene "OTTMUSG00000013495"; havana_gene_version "5"; transcript_name "Selenoh-001"; transcript_source "ensembl_havana"; transcript_biotype "protein_coding"; tag "CCDS"; ccds_id "CCDS16187"; havana_transcript "OTTMUST00000032615"; havana_transcript_version "2"; tag "seleno"; tag "basic"; transcript_support_level "1";

Any suggestion how to support this feature?

**Comment by tariqdaouda** [comment]
That's a tricky one. My first guess to store these modifications in the transcripts and apply them before translation.

**Comment by tariqdaouda** [comment]
No longer untranslated thanks to @courcelm 's pull request.
