### ISSUE TITLE
sqlite3:OperationalError:No such table: 

### ISSUE THREAD

**Issue by msejourne** [tariqdaouda/pyGeno#45]
Hi,

I was trying to import my Genome file and I followed your instruction in the doc. 

Start of importation is ok, it write "Importation begins!" progress is at 100% and an error occurs at following step : 
"almost done saving chromosomes...
\ progress[  ~-~-~-?:>                              ] ?% (1/?) runtime: ..."
Last  sentence of the message is : 
"sqlite3.OperationalError: no such table: main.RabaList_exons_for_Transcript_Raba"

How can I solve this problem ? 

Thanks for your help.

**Comment by tariqdaouda** [comment]
Hi,

Thanks for posting this one.
Could give write in the command you used to import the genome and the full traceback?

**Comment by tariqdaouda** [comment]
The pip version is lagging a bit behind the github version.

Could you try uninstalling everything:
```
pip uninstall rabaDB
pip uninstall pyGeno
```

And then installing the version on github:

```
git clone https://github.com/tariqdaouda/rabaDB/
cd rabaDB
python setup.py develop
cd ..

git clone https://github.com/tariqdaouda/pyGeno/
cd pyGeno
python setup.py develop
```

**Comment by msejourne** [comment]
I made your command lines , in root,  but my error is still here /:

>>> from pyGeno.importation.Genomes import *
>>> importGenome('/all/path/my_datawrap.tar.gz')
Importing genome package: /all/path/my_datawrap.tar.gz... (This may take a while)
Importing:
	description:  My mouse genome
	maintainer:  Unknown
	maintainer_contact:  Unknown
	version:  GRCm38.79
Genome:
	species:  Mus_musculus
	name:  GRCm38.my
	source:  Local
...
Importing gene set infos from /path/to/my/reference/Mus_musculus.GRCm38.79.gtf.gz...
Backuping indexes...
Droping all your indexes, (don't worry i'll restore them later)...
Parsing gene set...
Done. Importation begins!
- progress[~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-:>] 100.00% (1482012/1482011) runtime: 18.264sc, remaining: -0.000sc, avg: 0.000sc 

almost done saving chromosomes...
\ progress[  ~-~-~-?:>                              ] ?% (1/?) runtime: -1, remaining: ?, avg: -1.000sc 

saving genome object...
restoring core indexes...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Tools/pyGeno/pyGeno/importation/Genomes.py", line 179, in importGenome
    chros = _importGenomeObjects(gtfFile, chromosomeSet, genome, batchSize, verbose)
  File "/home/user/Tools/pyGeno/pyGeno/importation/Genomes.py", line 423, in _importGenomeObjects
    Transcript.ensureGlobalIndex('exons')
  File "/home/user/Tools/pyGeno/pyGeno/pyGenoObjectBases.py", line 223, in ensureGlobalIndex
    cls._wrapped_class.ensureIndex(fields)
  File "/home/user/Tools/rabaDB/rabaDB/Raba.py", line 510, in ensureIndex
    con.createIndex(name, 'anchor_raba_id')
  File "/home/user/Tools/rabaDB/rabaDB/rabaSetup.py", line 138, in createIndex
    self.execute(sql)
  File "/home/user/Tools/rabaDB/rabaDB/rabaSetup.py", line 224, in execute
    cur.execute(sql, values)
sqlite3.OperationalError: no such table: main.RabaList_exons_for_Transcript_Raba

**Comment by tariqdaouda** [comment]
What operating system are you using?

**Comment by msejourne** [comment]
I work on ubuntu 16.04 and python 2.7.12

**Comment by tariqdaouda** [comment]
That's weird I have just tested It on several Ubuntu-derived distributions (Mint, Lubuntu, Ubuntu mate)  + CentOS and it works on python 2.7.6 and 2.7.13. Could it be a problem with the installation sqlite on your machine?

**Comment by tariqdaouda** [comment]
No. However it's better if you use it inside a virtual environment. It is possible that you have some problems with the system-wide installation of sqlite3.

**Comment by msejourne** [comment]
I use a new virtual machine and I tried to install sqlite3 on several ways (download package ... make install and with apt-get install, in root or not) in to two ways I can create, open, update database.

In rabaDB and PyGeno I tested all import and there is no problems. 

When this error occurs I tried to open database and there is some tables inside.

**Comment by tariqdaouda** [comment]
could you try re-import the genome by deleting it first using the deleteGenome() function?
