### ISSUE TITLE
checkPythonVersion is not ready for python 3

### ISSUE THREAD

**Issue by courcelm** [tariqdaouda/pyGeno#51]
The checkPythonVersion will fail for some version of python 3.

It is not yet documented which version of python 3 is supported with pyGeno 2.0.0

**Comment by feghalya** [comment]
You are right, the documentation might not be clear enough regarding which python version to use! pyGeno 2.0.0 was tested with python 3.7 and above. Which python version are you using ?

**Comment by courcelm** [comment]
I got the error on 3.6.8 .

**Comment by feghalya** [comment]
The official python version for pyGeno is now 3.5 and above. checkPythonVersion was corrected along with the rest of the code.

I'm closing this issue now.
